### PR TITLE
PCL optimized for .NET 4.5

### PR DESCRIPTION
**Pull request by dmitry-shechtman**
Imported Base, updated project.json, cherry-picked and squashed :disappointed_relieved:

### CODE REVIEW

**Comment by dmitry-shechtman** [comment]
Not portable :sweat:

**Comment by dmitry-shechtman** [comment]
Right.

It took me some time, but I finally got the entire thing to work as intended.

**Comment by dmitry-shechtman** [comment]
...and now it's perfect :laughing:

**Comment by Knagis** [comment]
It seems that the `[Serializable]` attribute is no longer a problem?

**Comment by dmitry-shechtman** [comment]
Exceptions won't serialize in profile 259, just as they don't in profile 328 used in `Base`.

I did some shim work in https://github.com/AMDL/CommonMark.NET/tree/shim but I'm not sure it's worth the trouble. Note that it would require the user to install the package with a platform-specific implementation in the top-level project.

**Comment by Knagis** [comment]
Would it be possible to somehow check which version would the nuget manager pick for a non-portable .NET 4.5 target project? If it would pick the standalone 4.5 there should not be any problems by leaving the portable 4.5 exceptions as non-serializable.

The problem I want to avoid is someone upgrading the nuget dependency and ending up with the portable version where previously they used the standalone 4.5.

**Comment by dmitry-shechtman** [comment]
I just verified it. Here are the steps:

1. copy CommonMark.NET.0.11.0.nupkg $HOMEPATH\AppData\Local\NuGet\Cache
2. disconnect from the internet
3. install-package CommonMark.NET

**Comment by Knagis** [comment]
To clarify - nuget picks the 4.5-only version instead of the PCL? If that is so, I will merge this.

**Comment by dmitry-shechtman** [comment]
That's just how NuGet works. If the project is pure .NET 4.5, 4.5.1, 4.5.2 or even 4.6, and the package has `net45`, that will always be preferred over `portable-*`.

So yes, clearly and undoubtedly, NuGet will pick the 4.5-only version.

**Pull request merged**
