### PR TITLE
API doc comment improvements

### PR DESCRIPTION
**Pull request by fhaag**
Signed-off-by: Florian Haag <fhaag@users.sourceforge.net>

### CODE REVIEW

**Comment by fhaag** [comment]
This is a really tiny fix for what looks like a minor documentation error.

However, while we're at it - is there a specific reason why `null` values mentioned in the Xml API doc comments are written as `<c>null</c>`, rather than the "semantically stronger" `<see langword="null"/>`?

**Comment by Knagis** [comment]
> However, while we're at it - is there a specific reason why null values mentioned in the Xml API doc comments are written as <c>null</c>, rather than the "semantically stronger" <see langword="null"/>?

The only reason is that long ago when I started using tags in my comments I didn't notice that there is this kind of feature. Though even now the MSDN page on XML comment syntax does not mention the `langword` attribute: https://msdn.microsoft.com/en-us/library/acd0tfbe.aspx

**Comment by fhaag** [comment]
Indeed, the syntax `<see langword="null"/>` was only ever documented in an Xml documentation guide that is nowadays only [available via the Wayback Machine](http://web.archive.org/web/20080623060531/http://thoughtpad.net/alan-dean/cs-xml-documentation.html).

Nonetheless, it has worked consistently with everything that processes C# Xml comments that I have tried, and it provides the slight advantage that it gives whatever is displaying the documentation a chance to use a context-specific term - e.g. `Nothing` when using the library from VB.NET.

**Comment by Knagis** [comment]
If you're willing to "find-n-replace" I will merge that PR.

**Pull request merged**
