### PR TITLE
Added Visitor for HtmlPrinter (IHtmlPrinterVisitor and tests)

### PR DESCRIPTION
**Pull request by yetanotherchris**
I need to change the base url of all images and also for links, but individually (so I can't use the UrlResolver). This patch adds a visitor (`IHtmlPrinterVisitor`) to the `HtmlPrinter` class, and is configurable via the `CommonMarkdownSettings`. There's a few tests to illustrate how it works - you might need to change from tabs to spaces in the patch.

I'm not sure of the usefulness of OnExit in the interface, I've left it in but it's probably not much value.

### CODE REVIEW

**Comment by Knagis** [comment]
This issue seems to be covered by the solution described in #31 - note that the most probable solution to be included in the library is not the code in the PR but rather in the [`html-writer` branch](https://github.com/Knagis/CommonMark.NET/blob/html-writer/CommonMark/Formatters/HtmlFormatter.cs).

**Comment by Knagis** [comment]
If you could look at the code in the `html-writer` branch and test it out to see if it fits your needs, I would be grateful. I don't want to merge it in the master until it is clear that the chosen solution works.

**Comment by yetanotherchris** [comment]
I can update the commit so the visitor sits inside the `HtmlFormatter` class, but as it stands the `HtmlFormatter` class would need you to completely rewrite the `WriteBlock` or `WriteInline` methods to cater for custom links, so it offers a bit too much customisation for what I need.

I'm happy to add it to the other branch though if that's easier.

**Comment by Knagis** [comment]
How would your OnEnter help with rewriting the URL? Since it does not prevent the default HTML code from being generated, it would just render two links. You need to override `WriteInline`: 

```
class CustomHtmlFormatter : HtmlFormatter {
    protected override void WriteInline(Inline inline, bool isOpening, bool isClosing, out bool ignoreChildNodes) {
        if (inline.Tag == InlineTag.Link && isOpening && !this.RenderPlainTextInlines.Peek()) {
            this.Write("<a href=\"http://my/custom/link\">");
            ignoreChildNodes = false;
        }
        else {
            base.WriteInline(inline, isOpening, isClosing, out ignoreChildNodes);
        }
    }
}
```

**Comment by yetanotherchris** [comment]
Can't the `OnEnter` just change the `Inline` instance (unless the branch has changed)? The string that the method returns could be changed a void, that was just experimental.

**Comment by Knagis** [comment]
For the scenario you described, the new `HtmlFormatter` class would need less code than your approach. I don't see the need for `OnEnter` on that class.

If you could verify that the `HtmlFormatter` does indeed work for you, that would be one step closer to merging it into master and publishing a new version on nuget.

**Comment by yetanotherchris** [comment]
Actually I need to add a `class=""` to the tags as well, so the `HtmlFormatter` class is better suited - so a merge into master is good for me :+1:

**Comment by Knagis** [comment]
Closing since a different solution is implemented.

**Pull request closed without merging**
