### PR TITLE
Update core to use dotnet

### PR DESCRIPTION
**Pull request by Jeffiy**
Update core to use dotnet, but I'm not sure is it correct, please check it.

### CODE REVIEW

**Comment by Knagis** [comment]
Thanks! I will get to this in the next few weeks - seems that at least the appveyor build has to be reconfigured to support this change.

**Comment by Jeffiy** [comment]
@Knagis Done.

**Comment by Knagis** [comment]
The modified build does not execute the unit tests. Note that there are 4 failing tests right now on master.

Also I'm guessing that you discovered that appveyor does not yet support .NET Core builds natively - perhaps there is a ticket or issue registered somewhere that you could reference in the build script so that in the future it can be revisited to perhaps switch to native build instead of the external download.

**Comment by Knagis** [comment]
No answer from the PR author 😦

**Pull request closed without merging**
